#!/bin/sh

## From https://stackoverflow.com/questions/15015894/git-add-signed-off-by-line-using-format-signoff-not-working/46536244#46536244

NAME=$(git config user.name)
EMAIL=$(git config user.email)

## Checking $NAME and $EMAIL is no longer needed as git commit already checks
##
##if [ -z "$NAME" ]; then
##    echo "Please set user.name with git config user.name"
##    exit 1
##fi

##if [ -z "$EMAIL" ]; then
##    echo "Pleasae set user.email with git config user.email"
##    exit 1
##fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL>" \
    --in-place "$1"
